Enhance pre-commit hook.
Enhance pre-commit hook to include NPM audit, TypeScript type checking, and linting. Improved error handling and output messages for better developer experience.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,29 @@
-npm run precommit
-npm run precommit:check # Ensure type correctness
+echo -e "\n--------------------------------"
+echo -e "Running pre-commit hooks..."
 
 # Check if package.json or package-lock.json is staged
 if git diff --cached --name-only | grep -E 'package\.json|package-lock\.json' > /dev/null; then
   # Run npm audit and check for vulnerabilities
-  npm audit --audit-level=high
-  if [ $? -ne 0 ]; then
-    echo "Vulnerabilities found by NPM audit. Please fix them before committing."
+  if ! npm audit --audit-level=high > /dev/null; then
+    echo -e "[ERROR] Vulnerabilities found by NPM audit. Please fix them before committing."
+    echo -e "--------------------------------\n"
     exit 1
   fi
 fi
+
+# Check if any TypeScript files or config are staged
+if git diff --cached --name-only | grep -E '\.(ts|tsx)$|tsconfig\.json' > /dev/null; then
+  if ! npm run precommit:typecheck > /dev/null; then
+    echo -e "[ERROR] Run 'npm run precommit:typecheck' and fix the errors."
+    echo -e "--------------------------------\n"
+    exit 1
+  fi
+fi
+
+if ! lint-staged > /dev/null 2>&1; then
+  echo -e "[ERROR] Run 'npx lint staged' and fix the errors."
+  echo -e "--------------------------------\n"
+  exit 1
+fi
+
+echo -e "--------------------------------\n"
